### ISSUE TITLE
Cannot generate all Famous dataset for training

### ISSUE THREAD

**Issue by QtEngineer** [ErlerPhilipp/points2surf#23]

**Comment by QtEngineer** [comment]
I tried to use make_dataset.py to make famous_origin dataset for training but only got 3 files :
WARNING:only some output files are missing: ['datasets/famous_original/04_pts_vis/Utah_teapot_solid.xyz']
..., flower.xyz
..., Cup34.xyz

**Comment by QtEngineer** [comment]
both error accured when I tried to preproces ShapeNet with about 1000abjs,but only got 50

**Comment by ErlerPhilipp** [comment]
make_dataset.py has a parameter "num_max_faces", which filters all input meshes with more faces. you can set this to "None" to allow all meshes. the reason for this is that the SDF calculation in Trimesh takes very long, depending on the mesh complexity.

most ShapeNet objects have a very bad quality. when i tried, i couldn't even calculate vertex normals because of all the non-manifold pieces. you need either to clean the shapenet objects or use a different SDF calculation.

**Comment by QtEngineer** [comment]
thanks a lot！
