### ISSUE TITLE
How to get datasets with var,med and max noise?

### ISSUE THREAD

**Issue by QtEngineer** [ErlerPhilipp/points2surf#26]
Hi,
I tried to download ABC and Famous datastes and got vesion of original,free,and extra noise . It seems theres only one noisy datasets. Now I want to get datasets(or test datasets) with different levels of noise.Could you please provided them to me？Thanks！Looking forward to your reply.

**Comment by ErlerPhilipp** [comment]
ABC original is just called var-noise in the paper. It has the same settings as the ABC training set with random noise strength.

**Comment by QtEngineer** [comment]
Thanks a lot. I checked ABC test again: abc,abc_extra_noisy and abs_noisefree. I am no sure whether one of them is max noise vesion of 0.05L.

**Comment by Hxinyue** [comment]
Hello, I have my own building point cloud dataset in the format *.ply, what should I do about it that can be used for network training @ErlerPhilipp

**Comment by ErlerPhilipp** [comment]
Hi @Hxinyue,
please see this section in the readme: https://github.com/ErlerPhilipp/points2surf#dataset-from-point-clouds-for-reconstruction
Let me know if there are any problems.

**Comment by Hxinyue** [comment]
Hello, I downloaded a building point cloud data set with the file format of *. ply, such as building_ 01.ply is a point cloud file of a single building. What should I do to use it in network training or final generation? Because there may be many things I don't understand when I first came into contact with this aspect. I look forward to your reply and answer.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Philipp ***@***.***&gt;; 
发送时间: 2023年2月4日(星期六) 晚上6:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ErlerPhilipp/points2surf] How to get datasets with var,med and max noise? (Issue #26)






你好@心悦,
请参阅自述文件中的这一部分：https://github.com/ErlerPhilipp/points2surf#dataset-from-point-clouds-for-reconstruction
如果有什么问题告诉我。

—
直接回复此邮件，在GitHub上查看或取消订阅.
你收到这个是因为你被提到了。消息ID：<ErlerPhilipp/观点2 ***@***.***与&gt;.

**Comment by ErlerPhilipp** [comment]
Training is only possible if you can provide ground-truth meshes. We need the meshes to calculate ground-truth signed distances for supervised training.
Assuming you mean reconstruction with final generation, please see my answer in [your new issue](https://github.com/ErlerPhilipp/points2surf/issues/27). You need to choose a pre-trained model (e.g. max-model), create a new point cloud dataset and run a modified evaluation script.

**Comment by QtEngineer** [comment]
Thanks a lot ！
